version: '3'

services:
  backend:
    container_name: "docker-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    command: npm run start-dev
    depends_on:
      - mongo
    ports:
      - 4001:4000
    volumes:
      - ./backend/:/app
    environment:
      PORT: 5000

  mongo:
    container_name: "docker-mongo"
    image: mongo
    volumes:
      - ./backend/data:/data/db
    ports:
      - 27018:27017

  frontend:
    image: node:alpine
    container_name: "dockder-frontend"
    working_dir: /app
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app  


