version: '3'
services:
  app:
    container_name: "docker-app"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/app/src
    ports:
      - 3001:4000
    links:
      - mongo

  mongo:
    container_name: "docker-mongo"
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
